export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_FAILURE = 'ADD_TODO_FAILURE';
export const REMOVE_TODO_SUCCESS = 'REMOVE_TODO_SUCCESS';
export const REMOVE_TODO_FAILURE = 'REMOVE_TODO_FAILURE';
export const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS';
export const GET_TODOS_FAILURE = 'GET_TODOS_FAILURE';

export const ADD_MSG_SUCCESS = 'ADD_MSG_SUCCESS';
export const ADD_MSG_FAILURE = 'ADD_MSG_FAILURE';
export const REMOVE_MSG_SUCCESS = 'REMOVE_MSG_SUCCESS';
export const REMOVE_MSG_FAILURE = 'REMOVE_MSG_FAILURE';
export const GET_MSGS_SUCCESS = 'GET_MSGS_SUCCESS';
export const GET_MSGS_FAILURE = 'GET_MSGS_FAILURE';
